[package]
name = "the_rust_programming_language"
version = "0.1.0"
authors = ["Agent47 <654136828@qq.com>"]
edition = "2018"

[dependencies]
rand = "0.8.3"
#adder = "0.1.0"

[workspace]
members = [
    "adder",
    "add-one",
]